apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-val
  region: us-east-1

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

nodeGroups:
  - name: prod
    instanceType: t3.small
    desiredCapacity: 2
      
